(async function(){const id=TravelData.getParam('id');const all=await TravelData.getDays();const d=all.find(x=>x.id===id)||all.sort((a,b)=>new Date(b.date)-new Date(a.date))[0];
if(!d){document.body.innerHTML='<p>Kein Eintrag gefunden.</p>';return;} document.title=d.title+' – Ténéré Trip'; const $=s=>document.querySelector(s);
$('#dayTitle').textContent=d.title; $('#dayMeta').textContent=`${TravelData.formatDate(d.date)} · ${(d.location||'')}${d.km?' · '+d.km+' km':''}`; $('#dayText').innerHTML=(d.text||'').split('\n').map(p=>`<p>${p}</p>`).join('');
const gal=document.getElementById('gallery'); const photos=(d.photos||[]);
function derive(p){const b=p.replace(/^images\//,'').replace(/\.[^.]+$/,''); return {webp800:`images/opt/${b}-800.webp`, webp1600:`images/opt/${b}-1600.webp`, jpg1600:`images/opt/${b}-1600.jpg`, original:p};}
gal.innerHTML=photos.length?photos.map(p=>{const s=derive(p);return `<picture><source type="image/webp" srcset="${s.webp800} 800w, ${s.webp1600} 1600w" sizes="(min-width: 900px) 25vw, 50vw"><img src="${s.jpg1600}" alt="${d.title}" loading="lazy" decoding="async" onerror="this.onerror=null; this.src='${s.original}';"></picture>`}).join(''):'<p>Noch keine Fotos.</p>';
const map=L.map('map'); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap-Mitwirkende'}).addTo(map); L.control.scale().addTo(map);
const markers=[]; if(typeof d.start_lat==='number'&&typeof d.start_lng==='number') markers.push(L.marker([d.start_lat,d.start_lng]).bindPopup('Start'));
if(typeof d.end_lat==='number'&&typeof d.end_lng==='number') markers.push(L.marker([d.end_lat,d.end_lng]).bindPopup('Ende')); let fitted=false; if(markers.length){const g=L.featureGroup(markers).addTo(map); map.fitBounds(g.getBounds().pad(0.25)); fitted=true;}
const accent=getComputedStyle(document.documentElement).getPropertyValue('--gpx').trim()||'#a7adb1'; if(d.gpx){ new L.GPX(d.gpx,{async:true, polyline_options:{color:accent,weight:4,opacity:.95}, marker_options:{startIconUrl:null,endIconUrl:null,shadowUrl:null}}).on('loaded',e=>{ if(!fitted) map.fitBounds(e.target.getBounds().pad(0.2)); }).addTo(map);} if(!fitted&&!d.gpx){ map.setView([20,0],2); }})();