name: Optimize gallery images (CLI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - images/**
      - .github/workflows/resize-images-cli.yml

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # 1) Sharp-CLI global installieren (kein Node-Import, daher kein ESM-Ärger)
      - name: Install sharp-cli
        run: |
          npm install -g sharp-cli@^3

      # 2) Falls es keine Bilder gibt: sauber beenden
      - name: Skip if no images
        id: check
        run: |
          if [ ! -d images ]; then
            echo "no_images=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          count=$(find images -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.heic' -o -iname '*.heif' \) | wc -l)
          if [ "$count" -eq 0 ]; then
            echo "no_images=true" >> $GITHUB_OUTPUT
          fi

      # 3) Optimieren (Originale -> images/opt/*-800/1600.{jpg,webp})
     - name: Build optimized variants
  if: steps.check.outputs.no_images != 'true'
  shell: bash
  run: |
    shopt -s globstar nullglob
    for f in images/**/*.{jpg,JPG,jpeg,JPEG,png,PNG,webp,WEBP,heic,HEIC,heif,HEIF}; do
      # opt-Ordner überspringen
      case "$f" in images/opt/*) continue;; esac

      rel="${f#images/}"
      out_dir="images/opt/$(dirname "$rel")"
      name="$(basename "${rel%.*}")"
      mkdir -p "$out_dir"

      # JPEG 800/1600
      sharp -i "$f" -o "$out_dir/$name-800.jpg"  --autoOrient -f jpeg -q 82  resize 800  --withoutEnlargement
      sharp -i "$f" -o "$out_dir/$name-1600.jpg" --autoOrient -f jpeg -q 82  resize 1600 --withoutEnlargement

      # WEBP 800/1600
      sharp -i "$f" -o "$out_dir/$name-800.webp"  --autoOrient -f webp -q 82  resize 800  --withoutEnlargement
      sharp -i "$f" -o "$out_dir/$name-1600.webp" --autoOrient -f webp -q 82  resize 1600 --withoutEnlargement

      echo "✓ $f -> $out_dir/$name-{800,1600}.{jpg,webp}"
    done


      # 4) Änderungen committen
      - name: Commit optimized images
        if: steps.check.outputs.no_images != 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(images): optimize (CLI)"
          file_pattern: |
            images/opt/**
